# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PrfWMXXjrGdLvcMQ0p1tiVIb3obn78yg
"""

from tensorflow.keras.models import load_model

model = load_model('/content/drive/MyDrive/India Academia Connect AI Hackathon/Best_Model_weights_1.h5')

labels = dict({0: 'NON TEXT', 1: 'TEXT'})

labels

import os
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.preprocessing import image

dir_path = '/content/drive/MyDrive/India Academia Connect AI Hackathon/Dataset/test'
classifier_results = []
image_name = []
for img in os.listdir(dir_path):
  inp = image.load_img(dir_path+'//'+img, target_size=(224,224))
  
  test_image=img_to_array(inp) 
  test_image=test_image/255.0
  prediction_image=np.array(test_image)
  prediction_image= np.expand_dims(test_image, axis=0)
    
  pred = model.predict(prediction_image)
  print(pred)
  value = np.argmax(pred)
  print("Prediction: ", value)
  print("Prediction: ", labels[value])
  classifier_results.append(value)
  image_name.append(img)

  plt.imshow(inp)
  plt.show()

  print(img, "is classified as: " ,labels[value], value)

classifier_results

image_name

test_keys = image_name
test_values = classifier_results

res = {}
for key in test_keys:
  for value in test_values:
    res[key] = value
    test_values.remove(value)
    break

res



import json
import numpy

def convert(o):
    if isinstance(o, numpy.int64): return int(o)  
    raise TypeError

with open('personal_x.json', 'x') as json_file:
    json.dump(res, json_file, default=convert)

json_file